Module4 task1
htmlacademy-react/1551555-six-cities-11 pull request #5
Opened 2022-11-05 19:15 UTC by Grey201

2022-11-05 21:48 UTC, knenkne requested changes

2022-11-05 21:48 UTC, knenkne commented on project/src/components/app/app.tsx
> +              <PrivatRoute authorizationStatus={AuthorizationStatus.Auth}>
`PrivateRoute` опечатка в названии

2022-11-05 21:48 UTC, knenkne commented on project/src/components/app/app.tsx
> +                <FavoritesScreen offers={propsOffers}/>
А почему просто `offers` не назвать?

2022-11-05 21:48 UTC, knenkne commented on project/src/components/review/review.tsx
> +      defaultValue={''}
А почему здесь не используется `value` из стейта? Компонент же контролируемый

2022-11-05 21:48 UTC, knenkne commented on project/src/mocks/offers.ts
> +// ];
Если не надо - лучше удалить

2022-11-06 07:23 UTC, Grey201 commented on project/src/components/app/app.tsx
> +              <PrivatRoute authorizationStatus={AuthorizationStatus.Auth}>
ok

2022-11-06 20:17 UTC, merged